// <auto-generated />
using Hogwart.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hogwart.Api.src.Persistence.Migrations
{
    [DbContext(typeof(SortingContext))]
    [Migration("20230316194143_CreatedHousesAndStudentsTables")]
    partial class CreatedHousesAndStudentsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hogwart.Api.DTO.HouseDto", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("Hogwart.Api.DTO.StudentDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<bool>("DoesPlayQuidditch")
                        .HasColumnType("boolean");

                    b.Property<bool>("DoesSpeakParseltongue")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<float>("HeightInCentimeters")
                        .HasColumnType("real");

                    b.Property<string>("HouseDtoName")
                        .HasColumnType("text");

                    b.Property<bool>("IsAmbitious")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HouseDtoName");

                    b.ToTable("StudentDto");
                });

            modelBuilder.Entity("Hogwart.Api.DTO.StudentDto", b =>
                {
                    b.HasOne("Hogwart.Api.DTO.HouseDto", null)
                        .WithMany("Students")
                        .HasForeignKey("HouseDtoName");
                });

            modelBuilder.Entity("Hogwart.Api.DTO.HouseDto", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
